apiVersion: v1
kind: Namespace
metadata:
  name: turbonomic
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Xl.v1.charts.helm.k8s.io
  name: turbonomic-mkk5d
  namespace: turbonomic
spec:
  targetNamespaces:
    - turbonomic
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/t8c.turbonomic: ""
  name: t8c
  namespace: turbonomic
spec:
  name: t8c
  source: operatorhubio-catalog
  sourceNamespace: olm
